import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("monte_carlo_experiment.csv")

print("Колонки в файле:")
print(df.columns.tolist())
print("\nПервые 5 строк:")
print(df.head())

plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
plt.plot(df["N"], df["AreaWide"], marker="o", color='blue', label='Широкая область')
plt.axhline(y=df["ExactArea"].iloc[0], color='red', linestyle='--', label='Точная площадь')
plt.xlabel("Количество точек N")
plt.ylabel("Приближённая площадь")
plt.title("Приближённая площадь (широкая область)")
plt.legend()
plt.grid(True)

plt.subplot(2, 2, 2)
plt.plot(df["N"], df["ErrorWidePercent"], marker="o", color='blue')
plt.xlabel("Количество точек N")
plt.ylabel("Относительное отклонение (%)")
plt.title("Относительное отклонение (широкая область)")
plt.grid(True)

plt.subplot(2, 2, 3)
plt.plot(df["N"], df["AreaNarrow"], marker="s", color='green', label='Узкая область')
plt.axhline(y=df["ExactArea"].iloc[0], color='red', linestyle='--', label='Точная площадь')
plt.xlabel("Количество точек N")
plt.ylabel("Приближённая площадь")
plt.title("Приближённая площадь (узкая область)")
plt.legend()
plt.grid(True)

plt.subplot(2, 2, 4)
plt.plot(df["N"], df["ErrorNarrowPercent"], marker="s", color='green')
plt.xlabel("Количество точек N")
plt.ylabel("Относительное отклонение (%)")
plt.title("Относительное отклонение (узкая область)")
plt.grid(True)
plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(df["N"], df["ErrorWidePercent"], marker="o", linewidth=2, label='Широкая область')
plt.plot(df["N"], df["ErrorNarrowPercent"], marker="s", linewidth=2, label='Узкая область')
plt.xlabel("Количество точек N")
plt.ylabel("Относительное отклонение (%)")
plt.title("Сравнение относительного отклонения для разных областей")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
plt.plot(df["N"], df["ErrorWidePercent"], marker="o", linewidth=2, label='Широкая область')
plt.plot(df["N"], df["ErrorNarrowPercent"], marker="s", linewidth=2, label='Узкая область')
plt.xscale("log")
plt.xlabel("Количество точек N (log scale)")
plt.ylabel("Относительное отклонение (%)")
plt.title("Относительное отклонение в логарифмической шкале")
plt.legend()
plt.grid(True)
plt.show()
